name: Generate and Update PDF

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
          
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic pandoc
        pip install nbconvert

    - name: Convert Jupyter Notebook to PDF
      run: |
        jupyter nbconvert --to markdown formula1/f1.ipynb
        pandoc formula1/f1.md -o formula1/f1.pdf

    - name: Configure GIT
      run: |
          git config --global user.name "JabelResendiz"
          git config --global user.email "jabelresendiz18@gmail.com"

    - name: Commit
      run: |
        mv formula1/f1.pdf informe_F1.pdf
        git add informe_F1.pdf
        git commit -m "Update informe_F1.pdf on push"
         
        
    - name: Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/JabelResendiz/F1StatsLab 
        git push origin main 
